version: '2'


services:
  
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - DOCKERIZED=true
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    command: sh -c "npm start"
    depends_on:
      - backend

  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile 
    expose:
      - 8000
    volumes:
      - './api:/app/api'
      - './backend:/app/backend'
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
